// Generated by Wrangler on Thu Aug 01 2024 15:24:48 GMT+0900 (GMT+09:00)
// by running `wrangler types`

interface Env {
	SITE_NAME: "younagi.dev";
	SENDER: {"name":"younagi.dev Contact Email Sender","addr":"contact@younagi.dev"};
	RECIPIENT: {"name":"younagi.dev Contact Email Recipient","addr":"contact@younagi.dev"};
	SEB: SendEmail;
}
